%dw 2.0
output application/json
---
{
	active:  "true",
	activityDue:  "",
	additionalAssigneeList:  "",
	approval:  "",
	approvalHistory:  "",
	approvalSet:  "",
	assignedTo:  "",
	assignedGroup:  "",
	businessDuration:  "",
	businessService:  "",
	businessStc: "",
	calendarDuration:  "",
	calendarStc:  "",
	callerId:  "",
	category:  "",
	causedBy:  "",
	childIncidents:  "",
	closeNotes:  "",
	closeCode:  "",
	closedAt: "",
	closedBy:  "",
	cmdbCi:  "",
	comments: "This is from MUnit" ,
	commentsAndWorkNotes:  "This is from MUnit",
	company: "",
	contactType: "",
	correlationDisplay:  "",
	correlationId: "",
	deliveryPlan:  "",
	deliveryTask:  "",
	description:  "This is tested From MUNIT",
	dueDate:  "",
	escalation:  "",
	expectedStart: "",
	followUp: "",
	groupList:  "",
	holdReason:  "",
	impact:  "",
	incident_state:  "",
	knowlegde:  "",
	location: "",
	madeSla: "",
	notify: "",
	number: "",
	openedAt:  "",
	openedBy: "",
	order: "",
	parent:  "",
	parentIncident:  "",
	priority:  "High",
	problemId:  "",
	reassignmentCount:  "",
	reopenCount:   "",
	reopenedBy:  "",
	reopenedTime:  "",
	resolvedAt:  "",
	resolvedBy:  "",
	rfc:  "",
	severity:  "Low",
	shortDescription:"This is test from MUNIT",
	slaDue: "",
	state: "New" ,
	subCategory:  "",
	timeWorked: "",
	uponApproval:  "",
	uponReject: "",
	urgency:  "5",
	userInput:  "",
	watchList:  "",
	workEnd: "",
	workNotes:  "",
	workNotesList:  "",
	workStart: "",
	"sfdcCaseId":"5003k00000zSbwPAAS"
}